In [2]:
import numpy as np
it=[3,6,7,11]


In [17]:
n=np.array(it)
n

array([ 3,  6,  7, 11])

In [5]:
type(n)

numpy.ndarray

In [3]:
np.array({2,5,7})

array({2, 5, 7}, dtype=object)

In [4]:
d={"apple":100,"mango":200}
np.array(d)

array({'apple': 100, 'mango': 200}, dtype=object)

In [6]:
twod=np.array([[1,2],[3,4,5]])
twod

c:\program files\python36\lib\site-packages\ipykernel_launcher.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  """Entry point for launching an IPython kernel.


array([list([1, 2]), list([3, 4, 5])], dtype=object)

In [18]:
y=np.array([2,5,6,"7"])
y
y.shape

(4,)

In [12]:

list(range(9,16,2))



[9, 11, 13, 15]

In [29]:
a=np.arange(15,30,2)
a

array([15, 17, 19, 21, 23, 25, 27, 29])

In [3]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [23]:
# {  np.arange?   }
#to know details about arange ....open docstring
b= np.arange(15).reshape(3,5) # start from 0 to (15-1)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [7]:
np.array(range(7,0,-1))

array([7, 6, 5, 4, 3, 2, 1])

In [10]:
np.arange(40).reshape(8,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [29]:
arr1=np.arange(40)

In [30]:
arr2=arr1.reshape(8,5)

In [31]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [32]:
arr2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39]])

In [33]:
arr1[0]=500

In [34]:
arr2[0][1]=586

In [35]:
arr2

array([[500, 586,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39]])

In [36]:
arr1 is arr2

False